# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      DB_URL: ${{ secrets.DB_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}

      AWS_IMAGES_BUCKET: ${{ secrets.AWS_IMAGES_BUCKET }}
      AWS_IMAGES_SECRET: ${{ secrets.AWS_IMAGES_SECRET }}
      AWS_IMAGES_ID: ${{ secrets.AWS_IMAGES_ID }}

      MERCADOPAGO_CLIENT_ID: ${{ secrets.MERCADOPAGO_CLIENT_ID }}
      MERCADOPAGO_CLIENT_SECRET: ${{ secrets.MERCADOPAGO_CLIENT_SECRET }}

      MANTAINER_EMAIL: ${{ secrets.MANTAINER_EMAIL }}
      MANTAINER_PHONE: ${{ secrets.MANTAINER_PHONE }}
      APP_URL: ${{ secrets.APP_URL }}

      ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

      SECRET: ${{ secrets.SECRET }}
      ENV: ${{ secrets.ENV }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - run: yarn start & npx wait-on http://localhost:3000
    - run: yarn integration
